-- =============================================================================
-- Scenario Grid: Pre-computed "What If" Predictions
-- =============================================================================
--
-- Stores a grid of recession risk scores for different combinations of
-- 4 slider features (yield_spread, unrate, gdp_growth, cpi_yoy).
-- The remaining 7 features are held at their latest observed values.
--
-- Generated by src/recession_model.py after generate_predictions().
-- The dashboard reads this table for nearest-neighbor scenario lookup
-- without importing scikit-learn.
-- =============================================================================

CREATE TABLE IF NOT EXISTS scenario_grid (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,
    yield_spread            REAL NOT NULL,
    unrate                  REAL NOT NULL,
    gdp_growth_annualized   REAL NOT NULL,
    cpi_yoy                 REAL NOT NULL,
    probability             REAL NOT NULL,
    model_name              TEXT NOT NULL,
    generated_at            TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_scenario_grid_features
    ON scenario_grid (yield_spread, unrate, gdp_growth_annualized, cpi_yoy);
